# Generated by Django 5.1.1 on 2024-12-04 09:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('duree', models.PositiveIntegerField(help_text='Durée en minutes')),
                ('nom_prestataire', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photos', models.ImageField(blank=True, null=True, upload_to='photos/activites/')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nombre_adultes', models.PositiveIntegerField()),
                ('nombre_enfants', models.PositiveIntegerField()),
                ('duree_sejour', models.PositiveIntegerField(help_text='Durée en jours')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duree', models.PositiveIntegerField(help_text='Durée en jours')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itineraires', to='reservations.client')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='photos/hotels/')),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('note', models.DecimalField(decimal_places=1, help_text='La note doit être comprise entre 0 et 5.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('itineraires', models.ManyToManyField(blank=True, related_name='hotels', to='reservations.itineraire')),
            ],
        ),
        migrations.CreateModel(
            name='Deplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('voiture', 'Voiture'), ('minibus', 'Minibus'), ('bus', 'Bus')], max_length=50)),
                ('tarif_par_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacite', models.PositiveIntegerField()),
                ('itineraires', models.ManyToManyField(blank=True, related_name='deplacements', to='reservations.itineraire')),
            ],
        ),
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('activites', models.ManyToManyField(blank=True, related_name='jours', to='reservations.activite')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours', to='reservations.hotel')),
                ('itineraire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jours', to='reservations.itineraire')),
            ],
        ),
    ]
