# Generated by Django 5.1.1 on 2024-12-14 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='La note doit être comprise entre 0 et 5.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
