# Generated by Django 5.1.1 on 2024-12-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_hotel_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
