# Generated by Django 5.1.1 on 2024-12-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='total_chambres',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre total de chambres dans l'hôtel.", null=True),
        ),
    ]
