# Generated by Django 5.1.1 on 2024-12-15 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_hotel_total_chambres'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Itineraire', to='reservations.itineraire')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Facture', to='reservations.client')),
                ('jours', models.ManyToManyField(to='reservations.jour')),
            ],
        ),
    ]
