# Generated by Django 5.1.1 on 2024-12-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_rename_activite_jour_activites_activite_tarif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraire',
            name='prix',
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='tarif',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
