# Generated by Django 5.1.1 on 2024-12-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_itineraire_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='tarif',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
