# Generated by Django 5.1.1 on 2024-12-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_itineraire_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='tarif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
