# Generated by Django 5.1.1 on 2024-12-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_remove_jour_hotel_jour_chambres'),
    ]

    operations = [
        migrations.AddField(
            model_name='jour',
            name='tarif',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
