# Generated by Django 5.1.1 on 2024-12-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_jour_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deplacement',
            name='tarif_journalier',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jour',
            name='itineraire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jour_itineraire', to='reservations.itineraire'),
        ),
    ]
