# Generated by Django 5.1.1 on 2024-12-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_alter_deplacement_tarif_journalier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraire',
            name='payer',
            field=models.BooleanField(default=False),
        ),
    ]
